### ISSUE TITLE
Silence "raw prop works only when..." warning

### ISSUE THREAD

**Issue by lynndylanhurley** [sairion/svg-inline-react#14]
This warning is really annoying. Also, I'm not even using the `raw` prop. Would you accept a PR that allows for this warning to be disabled?

**Comment by aesopwolf** [comment]
@sairion ^

**Comment by sairion** [comment]
Yeah, I'll take it off. I usually use Chrome console filter frequently and mostly use console.debug for development but I can't expect people to do it.

**Comment by sairion** [comment]
f02724c
