### ISSUE TITLE
Need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by hutber** [sairion/svg-inline-react#18]
I am using the following code with react 

```
import React  from 'react';
import InlineSVG from 'svg-inline-react';


const Logo = React.createClass ({
    render() {
        return (
          <InlineSVG src={require("svg-inline-loader!../../../assets/Nopa_Logo.svg")} />
        );
    }
});

export default Logo;

```

**Package.json**
```
  "dependencies": {
    "babel-runtime": "^6.23.0",
    "eslint": "^3.17.1",
    "history": "^4.5.1",
    "react": "^15.4.2",
    "react-css-modules": "^4.1.0",
    "react-dom": "^15.4.2",
    "react-redux": "^5.0.3",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "react-router-redux": "^5.0.0-alpha.4",
    "redux": "^3.6.0",
    "rimraf": "^2.6.1",
    "stylelint": "^7.9.0",
    "url-loader": "^0.5.8",
    "webpack-config": "^7.0.0",
    "webpack": "^2.3.3"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.7",
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.0",
    "babel-preset-env": "^1.2.2",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-preset-stage-3": "^6.22.0",
    "babel-register": "^6.24.0",
    "commitizen": "^2.9.6",
    "css-loader": "^0.27.3",
    "css-modules-require-hook": "^4.0.6",
    "file-loader": "^0.10.1",
    "hutber-conventional-changelog": "^1.0.0",
    "immutable": "^3.8.1",
    "jsdom": "^9.12.0",
    "mocha": "^3.2.0",
    "nyc": "^10.2.0",
    "postcss-load-config": "^1.2.0",
    "postcss-loader": "^1.3.3",
    "postcss-nested": "^1.0.0",
    "postcss-simple-vars": "^3.0.0",
    "postcss-strip-inline-comments": "^0.1.5",
    "precss": "^1.4.0",
    "querystring": "^0.2.0",
    "react-hot-loader": "^3.0.0-beta.6",
    "redux-logger": "^3.0.0",
    "require-hacker": "^3.0.0",
    "resolve-url-loader": "^2.0.2",
    "style-loader": "^0.16.0",
    "svg-inline-loader": "^0.7.1",
    "svg-inline-react": "^2.0.0",
    "webpack-dashboard": "^0.3.0",
    "webpack-dev-server": "^2.4.2"
  },

```
```
ERROR in ./~/svg-inline-react/lib/index.js
Module parse failed: /var/www/zoo2test/node_modules/svg-inline-react/lib/index.js Unexpected token (9:24)
You may need an appropriate loader to handle this file type.
| 
| export default class InlineSVG extends React.Component {
|     static defaultProps = {
|         element: 'i',
|         raw: false,
 @ ./src/components/shared/logo/Logo.js 2:0-41
 @ ./src/components/Home/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index
webpack: Failed to compile.

```

**Comment by sairion** [comment]
Not sure what's exactly triggering it but I suspect something's not working well with class property.  Class property must be handled by `babel-preset-stage-2`(which they mention in https://babeljs.io/docs/plugins/preset-stage-2/) though, I think it is unnecessary to bring much complexity in this small package, so I'll take it off and declare it as ES2015-compatible. (fun.prop = prop)

**Comment by hutber** [comment]
Ye interesting, i am actually running `stage-2` through my babelrc. But ye :)

**Comment by sairion** [comment]
Please use 2.0.1 and reopen if any more issue occurs :)

**Comment by rafalmaciejewski** [comment]
This should be resolved in a much different way.
Many people are ignoring node_modules directory in their webpack loader's config. The way svg-inline-react is published doesn't allow that. To make it work you have to pass this library through specific webpack loader configuration.
I'm currently working on a quite big application that uses ~100 react-specific libraries, many of them are written in ES6/ES7 and svg-inline-react is the only one that requires to be transpiled to use. Because of this i'm unable to update to svg-inline-react 2.x.x.
The way it should be resolved is to keep your source files in a different directory than /lib. Before publishing, source files should be transpiled by babel and result should be outputted into /lib directory. This way the module could be consumed without the transpilation step and i wouldn't need a specific webpack configuration to use the library.

**Comment by grrowl** [comment]
sticking to v1 because even when I [transpile with babel-loader](https://github.com/webpack/webpack/issues/2031), it picks up the module's `.babelrc` and attempts to use plugins not listed in my project's dependencies:

```
ERROR in ./node_modules/svg-inline-react/lib/index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/project/node_modules/svg-inline-react"
    at /project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19```
```

if modules publish ES2015 code, it's much quicker for dependent projects to compile, and modules can be ES2015, ES2017+, and have type annotations, or be run on the server with less hassle. not to mention easier since [the expectation is already there](https://github.com/babel/babel-loader#babel-loader-is-slow)

**Comment by martpie** [comment]
Why? why on earth should I "babelize" myself an npm package, adding presets only for one lib? This issue made me move to `react-inline-svg`.
