### ISSUE TITLE
InlineSVG printing file location

### ISSUE THREAD

**Issue by ghost** [sairion/svg-inline-react#2]
Hello, I have some issue with InlineSVG not actually inlining the svg but the printing out the svg url instead, any idea what might be causing this? I use webpack file-loader so it passes the url for svg-inline-react

**Comment by sairion** [comment]
This component actually just wraps the input. You can use https://github.com/sairion/svg-inline-loader for actual inlining. If you want a component that actually inline svg from remote resource (using xhr, fetch, whatever), I have seen a few components out there it does it.

**Comment by ghost** [comment]
Got it, thank you!
