### ISSUE TITLE
The reason behind wrapping the svg in i tag?

### ISSUE THREAD

**Issue by iremlopsum** [sairion/svg-inline-react#28]
What is the reason behind wrapping the svg in an `<i>` tag?

Just wondering if there is a real reason, or this is just how it worked out?

**Comment by sairion** [comment]
it may not be needed, because we have `React.Fragment` now. But until React 15, if you want to put an `outerHTML` of a SVG element, you definitely need something to wrap. That's the only reason. also it resulted with making `raw` prop.

**Comment by sairion** [comment]
https://github.com/facebook/react/issues/12014 it seems it's still not possible to put raw html without wrapping element, I will resume current approach.
