### ISSUE TITLE
Packaging issues

### ISSUE THREAD

**Issue by ghost** [sairion/svg-inline-react#3]
Some issues I haver noticed with the svg-inline-react package:
- dist should not be in source-control but in npm (build/pre-publish)
- ES2015 users shouldn't have to import from 'svg-inline-react/lib', but just as CommonJS users from 'svg-inline-react/lib' which links to dist. In fact importing from 'svg-inline-react/lib' will cause some issues as most transpilers will not transpile anything that is in node_modules

**Comment by sairion** [comment]
I was not familiar with pre-publish but I will definitely do it. Thanks for tip!

I'm not getting your second point though, what kind of problem do you get and which transpilers do not transpile modules in `node_modules`? I'm confused.

**Comment by ghost** [comment]
Sorry, I did a typo, all users should just include 'svg-inline-react', because it should point to pre-transpiled code (dist presumably), it should not matter whether they are ES2015 users or not. Any packages in node_modules should typically already be pre-transpiled, and users' projects are typically setup not to transpile anything in node_modules.

By the way, not sure if you saw, there is some sort of inline SVG support coming to React RC15: https://twitter.com/reactjsnews/status/701843837350580224

**Comment by sairion** [comment]
Yeah, I got you what you are talking about. I wasn't very clear (and not ready) why someone might want to use (or include) ES2015 version. Some module bundler like Rollup or Webpack 2 takes advantage of ES module (but not entirely ES2015) so I thought someone might use it. Taking look at other projects setup, (like react-router) they require 'jsnext:main' to use. (if you want Webpack 2 to work with ES module, they have kinda different approach I'm afraid) I will clarify this on README, and other than es module feature (import / export declarations) it will be transpiled out.

P.S. Thanks for your tip, I missed it. There are a few loaders which can take advantage of svg support (directly prints out svg contents into a React component) but I can try different take on that. :)

**Comment by sairion** [comment]
Now distribution build is built on prepublish https://github.com/sairion/svg-inline-react/blob/master/package.json#L16
