### ISSUE TITLE
DOMParser detection in Safari

### ISSUE THREAD

**Issue by Guuz** [sairion/svg-inline-react#4]
The `DOMParser` detection might not be accurate. It detects that Safari doesn't support it:
![image](https://cloud.githubusercontent.com/assets/810327/13495058/a1f50098-e148-11e5-877c-b341406c07c8.png)
To my understanding it does: https://developer.mozilla.org/en/docs/Web/API/DOMParser
At the moment it will render and extra element in Safari because of this when using `raw={true}`.

**Comment by sairion** [comment]
Yeah, I had no idea Safari's `DOMParser` worked like that. I think I need to use `DOMParser.prototype.parseFromString` to detect it. Thanks!

**Comment by sairion** [comment]
Fixed via @689c7ddcd96c5da88474b5e89403ca1996f50b1d
https://github.com/sairion/svg-inline-react/blob/689c7ddcd96c5da88474b5e89403ca1996f50b1d/lib/index.js#L7-L9

**Comment by Guuz** [comment]
Thanks @sairion for the fix!
