### ISSUE TITLE
Update react peer-dependency to v15

### ISSUE THREAD

**Issue by alebiavati** [sairion/svg-inline-react#5]
Since react v15.0.0 RC is out, could we please update the peer dependency for react?

Without an updated peer-dependency `npm shrinkwrap` will fail on any project that uses `react@15.0.0-rc.x` and `svg-inline-react` modules:

```
>  npm shrinkwrap
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: react@^0.14.0, required by svg-inline-react@1.0.0
...
```

**Comment by sairion** [comment]
Just uploaded 1.0.1: http://npmsearch.com/?q=svg-inline-react
